### ISSUE TITLE
Plug doesn't play nice with private repositories

### ISSUE THREAD

**Issue by Crote** [andreyorst/plug.kak#47] opened 2019-02-10 00:44 UTC
I've been trying to get Plug to work with private Github repositories, but it doesn't really seem to work.

**Authenticated HTTP checkout:**
A regular `plug "crote/kakoune-my-private-plugin"` hangs on installation because it requires a username and password, which you can't provide. The only way to get out of this is by `kill -9`.

**SSH checkout:**
A `plug "git@github.com:Crote/kakoune-my-private-plugin.git"` does a proper checkout (but it probably only works for me because my machine prompts for a SSH passphrase using a GUI popup).
Afterwards, it never loads the plugin. Subsequent `plug-install` and `plug-list` invocations seem to indicate that it doesn't recognize that the cloned directory belongs to this url, so it's never recognised as properly installed. Renaming it to `plug "crote/kakoune-my-private-plugin"` after installation does make it work, including future updates.

----

I'm not sure if this is even worth fixing, but it would probably be nice to have the desired behaviour in this situation documented.

**Comment by andreyorst** [comment] 2019-02-10 15:57
>  Renaming it to `plug "crote/kakoune-my-private-plugin"` after installation does make it work, including future updates.
Well, this is weird I'll check it. That shouldn't happen.

As for authentication, I don't think that this can be fixed without introducing some kind of prompt for that on Kakoune side. Not sure if this should be opened as an issue in Kakoune repo, but I'm pretty sure that Kakoune shouldn't hang if git asks for password.

**Comment by andreyorst** [comment] 2019-02-10 16:10
Ah, I see what the problem is. When I clone my repos I never add `.git` at the end because I'm lazy, so my url is always look like so: `git@github.com:andreyorst/kakoune-my-private-plugin`, so when **plug.kak** loads plugin, it looks for the folder named `kakoune-my-private-plugin` because it strips off everything before last `/`. In your case **plug.kak** looked for the `kakoune-my-private-plugin.git` folder, and that's why it didn't worked. I'll fix it asap.

**Comment by andreyorst** [comment] 2019-02-10 16:49
the loading part should work fine now. As for password, I don't know what should be done

**Comment by Crote** [comment] 2019-02-10 18:36
Thanks for the quick fix! The `.git` suffix isn't something i'd type manually either, but that's what Github puts where when you copy the clone url.

About the password prompt, the Git manpage seems to suggest two options:

First, we can simply set `GIT_TERMINAL_PROMPT` to `0`, so git will simply fail to work and exit with code `128`: leave it up to the user to unlock the ssh key or add authentication to their http url (I really hope nobody would do this). Interestingly, despite a non-zero exit code and failure to clone, `plug` still reports a green "Done".

Second, we could set `GIT_ASKPASS`, which contains a command executed whenever Git needs a password. This could theoretically hook back into Kakoune, displaying a password prompt. Ugly, and probably not worth the effort.

**Comment by andreyorst** [comment] 2019-02-11 05:10
>  Interestingly, despite a non-zero exit code and failure to clone, `plug` still reports a green "Done".

Yes, when I've implemented the `*plug*` buffer, I wanted to handle git errors as well (and wanted a short log for each plugin), but it needs some refactoring and I had not much time back then. This will be fixed eventually. 

> Second, we could set `GIT_ASKPASS`, which contains a command executed whenever Git needs a password. This could theoretically hook back into Kakoune, displaying a password prompt. Ugly, and probably not worth the effort.

I'll think about it. But I still think that Kakoune should have some kind of prompt for passwords, for such cases. Maybe.

**Comment by andreyorst** [comment] 2019-02-12 14:52
@Crote @scarab5q I've created a [error-handling][1] branch, that displays error message with exit code, if download, or update ended with an error. Can you test it please?

[1]: https://github.com/andreyorst/plug.kak/tree/error-handling

**Closed** 2019-02-17 18:01 UTC
Labels: design flaw
