### ISSUE TITLE
Defer missing the hook

### ISSUE THREAD

**Issue by losnappas** [andreyorst/plug.kak#77] opened 2020-07-25 10:37 UTC
Hey,

I noticed this case where defer does not hook correctly.

```
hook global ModuleLoaded auto-pairs %{
        echo -debug 'this works'
}
plug 'alexherbo2/auto-pairs.kak' defer "auto-pairs" %{
	echo -debug 'this does not'
}
```

Maybe because it's required so soon? The module is declared and required in the same file.

**Comment by andreyorst** [comment] 2020-07-26 19:40
hello, thank you for the bug report. Please see https://discuss.kakoune.com/t/maintainance-warning-and-request

**Comment by andreyorst** [comment] 2021-02-26 21:45
@losnappas Hi, I'm back maintaining plugins. Can you please confirm that this still an issue?

**Comment by losnappas** [comment] 2021-02-27 23:07
Probably, but I started using https://github.com/alexherbo2/plug.kak/ :stuck_out_tongue:

**Comment by andreyorst** [comment] 2021-02-28 15:49
> Maybe because it's required so soon? 

No, this is not possible, the hook registered before the module is loaded.

I can't reproduce this:

![image](https://user-images.githubusercontent.com/19470159/109424680-a230fd00-79f5-11eb-896d-435b24c816b4.png)

Closing. Feel free to reopen in case this still happens.

**Comment by losnappas** [comment] 2021-02-28 15:54
The plugin has changed, so that's why.

The problem was that it had `require-module auto-pairs` in the same file: it would define the module at the top, then require it at the bottom.

So when you source the file, the `ModuleLoaded` hook would trigger right then, so need to add the hook _before_ sourcing the file.

**Comment by andreyorst** [comment] 2021-02-28 16:09
> The problem was that it had require-module auto-pairs in the same file: it would define the module at the top, then require it at the bottom.

I see, this might be problematic indeed. I'll look into this. There's no point in defining a module if you're going to require it at the end of the same file though.

**Comment by andreyorst** [comment] 2021-02-28 16:43
Hmm, this introduces one interesting issue.

I'm not sure what is the idiomatic way to write this kind of thing. Supposedly file a.kak creates a module:

``` kak
provide-module a %{
# impl
}
```

Then file b.kak registers a module-loaded hook whihc extends the module with a variable:

```
hook global ModuleLoaded a %{
decalre-variable a_extended ....
```

Then user installs this with plug.kak and uses the `defer` keyword like this:

```
plug "a-creator/a-plugin" defer a %{
    set-option a_extended "some value"
} config {
    map some keys
    require-module a
}
```

Currently hooks are prepended to the config. This results in the following order:

1. `plug` loads the file a.kak, which provides the module `a`
2. `plug` loads the file b.kak`, which registers the hook for module loading
3. `plug` constructs the following config:
   ```
   hook ModuleLoaded a %{ set-option a_extended "some value" }
   map some keys
   require-module a
   ```

This works, because hooks will be executed in the order they are registtered, and first hook will create the variable we're setting in the second hook.

I've tried to change the order as follows:

1. `plug` creates the hook `hook ModuleLoaded a %{ set-option a_extended "some value" }`
2. `plug` loads the file a.kak, which provides the module `a`
3. `plug` loads the file b.kak`, which registers the hook for module loading
4. `plug` constructs the following config:
   ```
   map some keys
   require-module a
   ```

And this fails, because we've created the hook before project hooks, and thus the variable is not yet defined.

I'm not sure if this is ideomatic or not to declare-variables inside ModuleLoaded hooks, or in hooks in general, but at least two of my other plugins do this. This smells bad when I think of it this way now.

**Comment by losnappas** [comment] 2021-02-28 23:53
To be honest, the extending thing you have makes more sense than requiring the module in the same file that one defines it in.

**Comment by andreyorst** [comment] 2021-03-01 18:47
The `demand` keyword had some pretty problematic implementation decisions, so I've changed it to work differently.

When plug.kak v2.0.0 will release, `demand` keyword will work almost the same ad `defer`, except it will inject `require-module` in `config` section in the order how config was specified. This allows `defer`/`demand` chaining. In both cases hooks are defined before any files are sourced.

**Comment by andreyorst** [comment] 2021-04-02 17:46
I've updated the plug.kak to new approach of handling configuration, so this issue should now be solved

**Closed by andreyorst** 2021-04-02 17:46 UTC
Labels: design flaw
