### ISSUE TITLE
Kakoune becomes unresponsive when requested git repo is wrong, could we get an error message instead?

### ISSUE THREAD

**Issue by scarab5q** [andreyorst/plug.kak#50] opened 2019-02-12 12:35 UTC
Had this issue for weeks until I just fixed it. Over this time I thought this  thought it was many things before I realised that I had pasted the repo name into the "plug" command wrong. To recreate put the following line into your kakrc:

`plug "alexherbo2/auto-pairs"`
(it should be auto-pairs.kak, yes this is the exact thing I have left in my kakrc for weeks it is really dumb for me to not have noticed this) 

This also works with any git repo that doesnt exist, I've tested it. Would it at all possible for the fifo buffer to display an error instead? Because of a mistake which is reletively easy to make this issue has plagued me for ages and I couldnt work out why. Just thought I'd point out this bug. Otherwise I love this, keep up the good work !

**Comment by andreyorst** [comment] 2019-02-12 13:19
Yeah, that's quite similar to another issue appeared not so long time before: #47 
Unfortunately I can't do much with private repos, and that's the case of such issue, if you try to clone this repo in the shell, it would ask for `Username` and `Password`:
```
$ git clone https://github.com/alexherbo2/auto-pairs
Cloning into 'auto-pairs'...
Username for 'https://github.com': vaiv
Password for 'https://vaiv@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/alexherbo2/auto-pairs/'
```
And you can't insert `Username`, and `Password` from Kakoune. The problem is, that this is default behavior for unexisting repos.

**Comment by andreyorst** [comment] 2019-02-12 14:54
I'm closing this in favor of #47 as it pretty the same issue. Let's continue the discussion there.

**Closed by andreyorst** 2019-02-12 14:54 UTC
